### ISSUE TITLE
about the result of magvit2

### ISSUE THREAD

**Issue by yyyouy** [TencentARC/Open-MAGVIT2#11]
Hello,
I was reviewing your implementation of MAGVIT2 and noticed a slight discrepancy in the ImageNet128 reconstruction results. The paper mentions an rFID of 1.15, while your GitHub repository lists it as 1.21. Could you clarify this difference?
Additionally, I'd be grateful for any suggestions on improving reproducibility to potentially achieve the reported 1.15 rFID.
Thank you for your time and assistance!

**Comment by RobertLuo1** [comment]
Hi, Thanks for your interest in our work. In this version, we have not adopted the deeper model setting, which can be seen in the below table.
![image](https://github.com/TencentARC/Open-MAGVIT2/assets/72377255/ec99d440-728c-4178-99f1-0e2cc367c6b5)
Since Magvit2 adopts Resnet as the perceptual model which is not quite prevalent in IQA or other Tokenizer training, we think it is relatively hard to fully achieve the quite promising results of 1.15 rFID.
